import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("statically exports the photo contest matching experience", async () => {
  const html = await readFile(new URL("../out/index.html", import.meta.url), "utf8");
  assert.match(html, /<html lang="ja"/i);
  assert.match(html, /写真コンテストものさし/);
  assert.match(html, /この一枚を、[\s\S]*どこへ出せるか/);
  assert.match(html, /写真は任意です/);
  assert.match(html, /世界から応募できる賞・オープンコール/);
  assert.match(html, /139[\s\S]{0,20}の応募ルート/);
  assert.match(html, /応募候補/);
  assert.match(html, /地方公募の調査台帳/);
  assert.match(html, /確認済みの都道府県/);
  assert.match(html, /未収録・確認中/);
  assert.match(html, /北海道/);
  assert.match(html, /長崎県/);
  assert.match(html, /フォーム以外の入口/);
  assert.match(html, /11[\s\S]{0,80}週次・月次・常設入口/);
  assert.match(html, /使える見込み/);
  assert.match(html, /NatGeo Your Shot/);
  assert.match(html, /#PhotoVogueMonday/);
  assert.match(html, /Flickr Friday/);
  assert.match(html, /LFI Gallery/);
  assert.match(html, /VIEWBUG/);
  assert.match(html, /過去作を読む手掛かり/);
  assert.match(html, /\/og\.png/);
  assert.doesNotMatch(html, /react-loading-skeleton|codex-preview|Starter Project/);
});

test("seed data keeps application routes and evidence auditable", async () => {
  const [opportunitiesText, worldwideText, socialText, domesticText, discoveryText, trendsText, page, layout, packageJson, qualityReport] =
    await Promise.all([
      readFile(new URL("../data/opportunities.json", import.meta.url), "utf8"),
      readFile(new URL("../data/worldwide-opportunities.json", import.meta.url), "utf8"),
      readFile(new URL("../data/social-opportunities.json", import.meta.url), "utf8"),
      readFile(new URL("../data/domestic-opportunities.json", import.meta.url), "utf8"),
      readFile(new URL("../data/discovery-channels.json", import.meta.url), "utf8"),
      readFile(new URL("../data/trends.json", import.meta.url), "utf8"),
      readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
      readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
      readFile(new URL("../package.json", import.meta.url), "utf8"),
      readFile(new URL("../public/quality-report.html", import.meta.url), "utf8"),
    ]);
  const opportunities = JSON.parse(opportunitiesText);
  const worldwide = JSON.parse(worldwideText);
  const social = JSON.parse(socialText);
  const domestic = JSON.parse(domesticText);
  const discovery = JSON.parse(discoveryText);
  const trends = JSON.parse(trendsText);

  assert.equal(opportunities.length, 16);
  assert.equal(worldwide.length, 24);
  assert.equal(social.length, 2);
  assert.equal(domestic.length, 97);
  assert.equal(discovery.length, 11);
  const allOpportunities = [...opportunities, ...worldwide, ...social, ...domestic];
  assert.equal(new Set(allOpportunities.map((item) => item.id)).size, 139);
  assert.ok(allOpportunities.every((item) => ["2026-07-23", "2026-07-24", "2026-07-31"].includes(item.verifiedAt)));
  assert.ok(allOpportunities.every((item) => item.sourceUrl.startsWith("https://")));
  assert.ok(allOpportunities.every((item) => !Number.isNaN(Date.parse(item.deadline))));
  assert.ok(allOpportunities.every((item) => Object.keys(item.evidence).length === 8));
  assert.ok(worldwide.every((item) => item.applicantScope === "worldwide"));
  assert.ok(worldwide.every((item) => item.entryLanguage && item.organizerRegion));
  assert.ok(worldwide.some((item) => item.organizerRegion === "中東"));
  assert.ok(worldwide.some((item) => item.organizerRegion === "ヨーロッパ"));
  assert.equal(worldwide.find((item) => item.id === "hipa-determination-2026")?.feeType, "unknown");
  assert.equal(worldwide.find((item) => item.id === "bifa-professional-2026")?.evidence.technical, "conflict");
  assert.equal(worldwide.find((item) => item.id === "unesco-youth-eyes-silk-roads-2026")?.evidence.deadline, "conflict");
  assert.equal(worldwide.find((item) => item.id === "xposure-international-photography-awards-2026")?.feeType, "free");
  const cpa = worldwide.find((item) => item.id === "cpa-international-juried-exhibition-2026");
  assert.equal(cpa?.applicantScope, "worldwide");
  assert.equal(cpa?.submissionMethod, "platform_upload");
  assert.equal(cpa?.deadline, "2026-10-02T05:59:00Z");
  assert.equal(cpa?.aiPolicy, "needs_check");
  const lensculturePhotobook = worldwide.find((item) => item.id === "lensculture-photobook-prize-2026");
  assert.equal(lensculturePhotobook?.eligibleFromJapan, true);
  assert.equal(lensculturePhotobook?.workType, "series");
  assert.equal(lensculturePhotobook?.seriesMin, 20);
  assert.equal(lensculturePhotobook?.seriesMax, 30);
  assert.equal(lensculturePhotobook?.aiPolicy, "photo_origin_required");
  const chromaticRoutes = worldwide.filter((item) => item.id.startsWith("chromatic-"));
  assert.equal(chromaticRoutes.length, 2);
  assert.deepEqual(chromaticRoutes.map((item) => item.entrantRole).sort(), ["nonprofessional", "professional"]);
  assert.ok(chromaticRoutes.every((item) => item.deadline === "2026-10-25"));
  assert.ok(chromaticRoutes.every((item) => item.tones.join(",") === "color"));
  const monovisionsRoutes = worldwide.filter((item) => item.id.startsWith("monovisions-"));
  assert.equal(monovisionsRoutes.length, 2);
  assert.deepEqual(monovisionsRoutes.map((item) => item.workType).sort(), ["series", "single"]);
  assert.ok(monovisionsRoutes.every((item) => item.deadline === "2027-05-16"));
  assert.ok(monovisionsRoutes.every((item) => item.tones.join(",") === "monochrome"));
  assert.ok(monovisionsRoutes.every((item) => item.publicationPolicy === "allowed" && item.priorAwardPolicy === "allowed"));
  assert.equal(worldwide.find((item) => item.id === "monovisions-series-2027")?.seriesMin, 2);
  assert.equal(worldwide.find((item) => item.id === "monovisions-series-2027")?.seriesMax, 8);
  const graphis = worldwide.find((item) => item.id === "graphis-photography-awards-2027");
  assert.equal(graphis?.entrantRole, "professional");
  assert.equal(graphis?.deadline, "2026-11-17");
  assert.equal(graphis?.aiPolicy, "separate_category");
  assert.equal(graphis?.rightsPolicy, "explicit");
  const formUnseen = worldwide.find((item) => item.id === "form-photo-award-unseen-2027");
  assert.equal(formUnseen?.opportunityKind, "open_call");
  assert.equal(formUnseen?.deadline, "2026-10-31T22:59:00Z");
  assert.equal(formUnseen?.seriesMin, 1);
  assert.equal(formUnseen?.seriesMax, 8);
  assert.equal(formUnseen?.minLongEdge, 1500);
  assert.equal(formUnseen?.rightsPolicy, "explicit");
  assert.equal(social.find((item) => item.id === "photovogue-global-open-call-2026")?.submissionMethod, "platform_upload");
  assert.equal(social.find((item) => item.id === "apec-main-influencer-2026")?.submissionMethod, "hybrid");
  assert.equal(social.find((item) => item.id === "apec-main-influencer-2026")?.eligibleFromJapan, true);
  assert.ok(domestic.every((item) => item.organizerCountry === "日本"));
  assert.ok(domestic.every((item) => item.status === "open" || item.status === "expected"));
  assert.equal(domestic.find((item) => item.id === "jps-nonfiction-photo-award-2026")?.submissionMethod, "mail_or_in_person");
  assert.equal(domestic.find((item) => item.id === "jps-nonfiction-photo-award-2026")?.seriesMin, 15);
  assert.equal(domestic.find((item) => item.id === "jps-nonfiction-photo-award-2026")?.seriesMax, 30);
  assert.equal(domestic.filter((item) => item.id.startsWith("canon-photo-contest-60-")).length, 2);
  assert.equal(domestic.filter((item) => item.id.startsWith("tamron-photo-contest-2026-")).length, 2);
  assert.equal(domestic.filter((item) => item.id.startsWith("tamron-train-2026-")).length, 2);
  assert.equal(domestic.filter((item) => item.id.startsWith("bdk-hotoke-heart-2026-")).length, 2);
  assert.equal(domestic.find((item) => item.id === "national-parks-japan-photo-contest-2026")?.requiresPublicSocial, true);
  assert.equal(domestic.find((item) => item.id === "kinkan-photo-contest-2026")?.submissionMethod, "hybrid");
  const localRoutes = domestic.filter((item) => item.shootingPrefectures?.length);
  assert.equal(localRoutes.length, 78);
  assert.equal(new Set(localRoutes.flatMap((item) => item.shootingPrefectures)).size, 47);
  assert.ok(localRoutes.every((item) => item.shotLocationRule));
  assert.deepEqual(domestic.find((item) => item.id === "utashinai-smallest-photo-contest-2026")?.shootingPrefectures, ["北海道"]);
  assert.deepEqual(domestic.find((item) => item.id === "goto-world-heritage-island-photo-2026")?.shootingPrefectures, ["長崎県"]);
  assert.deepEqual(domestic.find((item) => item.id === "aomori-nebuta-photo-contest-2026")?.shootingPrefectures, ["青森県"]);
  assert.deepEqual(domestic.find((item) => item.id === "fukui-life-favorite-curation-2026")?.shootingPrefectures, ["福井県"]);
  assert.deepEqual(domestic.find((item) => item.id === "daisen-oki-national-park-90-photo-contest")?.shootingPrefectures, ["鳥取県", "島根県", "岡山県"]);
  assert.equal(domestic.find((item) => item.id === "daisen-oki-national-park-90-photo-contest")?.workType, "unknown");
  assert.deepEqual(domestic.find((item) => item.id === "okinawa-fukugi-digital-photo-contest-13")?.shootingPrefectures, ["沖縄県"]);
  assert.ok(domestic.find((item) => item.id === "ehime-prefectural-assembly-high-school-photo-contest-2")?.localEligibilityLabel);
  assert.deepEqual(domestic.find((item) => item.id === "misaki-town-photo-contest-2026")?.shootingPrefectures, ["大阪府"]);
  assert.deepEqual(domestic.find((item) => item.id === "nakatsu-instagram-photo-contest-2026-july")?.shootingPrefectures, ["大分県"]);
  assert.equal(domestic.find((item) => item.id === "mugi-minami-photo-contest-2026")?.status, "expected");
  assert.deepEqual(domestic.find((item) => item.id === "fuji-oishi-hana-terrace-summer-photo-contest-2026")?.shootingPrefectures, ["山梨県"]);
  assert.deepEqual(domestic.find((item) => item.id === "akabira-photo-contest-2026")?.shootingPrefectures, ["北海道"]);
  assert.equal(domestic.find((item) => item.id === "good-ishikari-photo-contest-2026")?.aiPolicy, "photo_origin_required");
  assert.equal(domestic.find((item) => item.id === "hashima-no-miryoku-2026")?.opportunityKind, "curation");
  assert.equal(domestic.find((item) => item.id === "ichikikushikino-photo-contest-2026")?.rightsPolicy, "explicit");
  const bonphoto = domestic.find((item) => item.id === "nipponkodo-bonphoto-2026");
  assert.equal(bonphoto?.eligibleFromJapan, true);
  assert.equal(bonphoto?.requiresPublicSocial, true);
  assert.equal(bonphoto?.editPolicy, "allowed_with_limits");
  const yumenoshima = domestic.find((item) => item.id === "yumenoshima-photo-contest-2026");
  assert.deepEqual(yumenoshima?.shootingPrefectures, ["東京都"]);
  assert.equal(yumenoshima?.rightsPolicy, "explicit");
  assert.equal(yumenoshima?.simultaneousPolicy, "not_allowed");
  const kanazawaFireworks = domestic.find((item) => item.id === "kanazawa-matsuri-fireworks-photo-contest-52");
  assert.equal(kanazawaFireworks?.status, "expected");
  assert.deepEqual(kanazawaFireworks?.shootingPrefectures, ["神奈川県"]);
  assert.equal(kanazawaFireworks?.evidence.technical, "explicit");
  const ogawara = domestic.find((item) => item.id === "ogawara-town-photo-contest-2026");
  assert.deepEqual(ogawara?.shootingPrefectures, ["宮城県"]);
  assert.equal(ogawara?.evidence.technical, "conflict");
  assert.equal(ogawara?.requiresPublicSocial, true);
  const nihonmatsuInstagram = domestic.find((item) => item.id === "nihonmatsu-tourism-photo-contest-2026-instagram");
  assert.equal(nihonmatsuInstagram?.submissionMethod, "hybrid");
  assert.ok(nihonmatsuInstagram?.requiredTags?.includes("#安達太良山"));
  const nihonmatsuPrint = domestic.find((item) => item.id === "nihonmatsu-tourism-photo-contest-2026-print");
  assert.equal(nihonmatsuPrint?.status, "expected");
  assert.equal(nihonmatsuPrint?.categorySelectionRequired, true);
  const ubekitaSpringSummer = domestic.find((item) => item.id === "ubekita-photo-contest-2026-spring-summer");
  assert.equal(ubekitaSpringSummer?.status, "open");
  assert.deepEqual(ubekitaSpringSummer?.shootingPrefectures, ["山口県"]);
  assert.equal(ubekitaSpringSummer?.editPolicy, "basic_only");
  const ubekitaAutumnWinter = domestic.find((item) => item.id === "ubekita-photo-contest-2026-autumn-winter");
  assert.equal(ubekitaAutumnWinter?.status, "expected");
  assert.equal(ubekitaAutumnWinter?.deadline, "2027-02-19");
  const hanabiAmu = domestic.find((item) => item.id === "hanabi-amu-fireworks-photo-contest-2026");
  assert.equal(hanabiAmu?.status, "expected");
  assert.deepEqual(hanabiAmu?.shootingPrefectures, ["秋田県"]);
  assert.equal(hanabiAmu?.entryLimit, 3);
  const kawasakiSenior = domestic.find((item) => item.id === "kawasaki-senior-photo-contest-2026");
  assert.equal(kawasakiSenior?.status, "expected");
  assert.equal(kawasakiSenior?.applicantScope, "limited");
  assert.equal(kawasakiSenior?.entryLimit, 2);
  assert.equal(kawasakiSenior?.maxFileMB, 5);
  const yawataSmallFriends = domestic.find((item) => item.id === "yawata-small-friends-photo-contest-2026");
  assert.deepEqual(yawataSmallFriends?.shootingPrefectures, ["京都府"]);
  assert.equal(yawataSmallFriends?.shotYearFrom, 2026);
  assert.equal(yawataSmallFriends?.simultaneousPolicy, "not_allowed");
  const hachinoheWaterRoutes = domestic.filter((item) => item.id.startsWith("hachinohe-water-life-photo-contest-2026-"));
  assert.equal(hachinoheWaterRoutes.length, 2);
  assert.ok(hachinoheWaterRoutes.every((item) => item.applicantScope === "worldwide"));
  assert.ok(hachinoheWaterRoutes.every((item) => item.formats.join(",") === "image/jpeg" && item.maxFileMB === 5));
  assert.equal(hachinoheWaterRoutes.find((item) => item.id.endsWith("-oraho"))?.entryLimit, 2);
  assert.equal(hachinoheWaterRoutes.find((item) => item.id.endsWith("-minna"))?.entryLimit, 1);
  const enaPhoto = domestic.find((item) => item.id === "ena-photo-movie-contest-2026-photo");
  assert.equal(enaPhoto?.status, "expected");
  assert.equal(enaPhoto?.workType, "both");
  assert.deepEqual(enaPhoto?.shootingPrefectures, ["岐阜県"]);
  const mitaneCover = domestic.find((item) => item.id === "mitane-newsletter-cover-photo-contest-2026");
  assert.equal(mitaneCover?.entryLimit, 2);
  assert.deepEqual(mitaneCover?.shootingPrefectures, ["秋田県"]);
  const gifuTourismRoutes = domestic.filter((item) => item.id.startsWith("gifu-tourism-photo-contest-2026-"));
  assert.equal(gifuTourismRoutes.length, 2);
  assert.deepEqual(gifuTourismRoutes.map((item) => item.submissionMethod).sort(), ["hashtag", "mail_or_in_person"]);
  assert.ok(gifuTourismRoutes.every((item) => item.aiPolicy === "not_allowed" && item.rightsPolicy === "explicit"));
  assert.equal(gifuTourismRoutes.find((item) => item.id.endsWith("-instagram"))?.requiresPublicSocial, true);
  const sakaide = domestic.find((item) => item.id === "sakaide-ohashi-matsuri-photo-contest-61");
  assert.deepEqual(sakaide?.shootingPrefectures, ["香川県"]);
  assert.equal(sakaide?.submissionMethod, "hybrid");
  assert.equal(sakaide?.editPolicy, "basic_only");
  const sakaiAsean = domestic.find((item) => item.id === "sakai-asean-photo-contest-2026");
  assert.equal(sakaiAsean?.applicantScope, "worldwide");
  assert.equal(sakaiAsean?.minAge, 18);
  assert.equal(sakaiAsean?.maxFileMB, 10);
  assert.equal(sakaiAsean?.rightsPolicy, "explicit");
  const nihonkaiParkline = domestic.find((item) => item.id === "nihonkai-parkline-photo-contest-2026");
  assert.deepEqual(nihonkaiParkline?.shootingPrefectures, ["山形県", "新潟県"]);
  assert.equal(nihonkaiParkline?.submissionMethod, "hashtag");
  assert.ok(nihonkaiParkline?.requiredTags?.includes("#日本海パークラインフォトコン2026"));
  assert.equal(nihonkaiParkline?.rightsPolicy, "explicit");
  const goseTourism = domestic.find((item) => item.id === "gose-tourism-photo-contest-38");
  assert.equal(goseTourism?.status, "expected");
  assert.deepEqual(goseTourism?.shootingPrefectures, ["奈良県"]);
  assert.equal(goseTourism?.aiPolicy, "not_allowed");
  assert.equal(goseTourism?.rightsPolicy, "explicit");
  const shimoyama = domestic.find((item) => item.id === "shimoyama-photo-contest-2026");
  assert.equal(shimoyama?.submissionMethod, "hybrid");
  assert.ok(shimoyama?.requiredTags?.includes("#2026しもやまフォトコン"));
  assert.equal(shimoyama?.simultaneousPolicy, "not_allowed");
  assert.equal(shimoyama?.editPolicy, "no_composite");
  const aizuwakamatsuTakara = domestic.find((item) => item.id === "aizuwakamatsu-takara-sagashi-photo-contest-2026");
  assert.equal(aizuwakamatsuTakara?.applicantScope, "limited");
  assert.deepEqual(aizuwakamatsuTakara?.eligibleResidenceGroups, ["japan"]);
  assert.equal(aizuwakamatsuTakara?.categorySelectionRequired, true);
  assert.equal(aizuwakamatsuTakara?.aiPolicy, "photo_origin_required");
  assert.equal(aizuwakamatsuTakara?.rightsPolicy, "explicit");
  const headOn = worldwide.find((item) => item.id === "head-on-photo-awards-2026");
  assert.equal(headOn?.deadline, "2026-08-16T13:59:00Z");
  assert.equal(headOn?.applicantScope, "worldwide");
  assert.equal(headOn?.categorySelectionRequired, true);
  assert.equal(headOn?.formats.join(","), "image/jpeg");
  assert.equal(headOn?.aiPolicy, "photo_origin_required");
  const photography212 = worldwide.find((item) => item.id === "international-212-photography-competition-2026");
  assert.equal(photography212?.deadline, "2026-09-06T20:59:00Z");
  assert.equal(photography212?.seriesMin, 5);
  assert.equal(photography212?.seriesMax, 10);
  assert.equal(photography212?.evidence.technical, "conflict");
  assert.equal(photography212?.rightsPolicy, "explicit");
  assert.equal(domestic.find((item) => item.id === "mogami-oguni-river-photo-contest-2026")?.rightsPolicy, "needs_check");
  assert.equal(domestic.find((item) => item.id === "fukui-life-favorite-curation-2026")?.opportunityKind, "curation");
  assert.ok(discovery.every((item) => item.verifiedAt === "2026-07-23"));
  assert.ok(discovery.every((item) => Object.keys(item.evidence).length === 7));
  assert.ok(discovery.find((item) => item.id === "natgeo-your-shot")?.requiredTags.includes("#NatGeoYourShot"));
  assert.equal(discovery.find((item) => item.id === "natgeo-your-shot")?.capturePolicy, "within_6_months");
  assert.ok(discovery.find((item) => item.id === "photovogue-monday")?.requiredTags.includes("#PhotoVogueMonday"));
  assert.equal(discovery.find((item) => item.id === "photovogue-full-projects")?.pathType, "email");
  assert.equal(discovery.find((item) => item.id === "flickr-friday")?.capturePolicy, "new_after_announcement");
  assert.deepEqual(discovery.find((item) => item.id === "lfi-leica-mastershots")?.eligibleDeviceGroups, ["leica"]);
  assert.equal(opportunities.filter((item) => item.id.startsWith("sony-single-")).length, 10);
  assert.ok(trends.length >= 4);
  assert.ok(trends.every((item) => item.url.startsWith("https://")));
  assert.match(page, /localStorage/);
  assert.match(page, /URL\.createObjectURL/);
  assert.match(page, /未回答を推測で埋めず/);
  assert.match(page, /提出準備/);
  assert.match(page, /worldwideOpportunityData/);
  assert.match(page, /socialOpportunityData/);
  assert.match(page, /domesticOpportunityData/);
  assert.match(page, /discoveryChannelData/);
  assert.match(page, /assessDiscovery/);
  assert.match(page, /使える見込み/);
  assert.match(page, /captureDevice/);
  assert.match(page, /capturePrefecture/);
  assert.match(page, /地方公募の調査台帳/);
  assert.match(page, /47-PREFECTURE RESEARCH LEDGER/);
  assert.match(page, /shootingPrefectures/);
  assert.match(page, /platformEntry/);
  assert.match(page, /国内・海外の表示切替/);
  assert.match(page, /marketFilter/);
  assert.match(page, /海外・国際公募/);
  assert.match(page, /social_allowed/);
  assert.match(page, /世界各国から応募可/);
  assert.match(page, /フォーム以外の入口/);
  assert.match(page, /\/quality-report\.html/);
  assert.match(layout, /metadataBase/);
  assert.doesNotMatch(layout, /next\/headers/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
  assert.match(qualityReport, /139/);
  assert.match(qualityReport, /47\/47/);
  assert.match(qualityReport, /67\.5%/);
  assert.match(qualityReport, /夜間公式再確認で追加した(?:3|8|11|13|17|19|23|25|28|30|33)ルート/);
  assert.match(qualityReport, /お盆っていいなフォトコンテスト2026/);
  assert.match(qualityReport, /夢の島フォトコンテスト2026/);
  assert.match(qualityReport, /MonoVisions Photography Awards 2027/);
  assert.match(qualityReport, /Graphis Photography Awards 2027/);
  assert.match(qualityReport, /Form Photo Award x UNSEEN 2027/);
  assert.match(qualityReport, /アセアンフォトコンテスト2026/);
  assert.match(qualityReport, /瀬波・あつみ温泉・笹川流れフォトコンテスト2026/);
  assert.match(qualityReport, /Head On Photo Awards 2026/);
  assert.match(qualityReport, /International 212 Photography Competition 2026/);
  assert.match(qualityReport, /第38回御所市観光フォトコンテスト/);
  assert.match(qualityReport, /しもやまフォトコンテスト/);
  assert.match(qualityReport, /会津の宝探し フォトコンテスト2026/);
});
